opret, gem, vis, slet arvelader
NillasOrg/Arvefordeleren pull request #12
Opened 2024-11-12 20:49 UTC by fredforrest

blazor magi

2024-11-12 21:03 UTC, NillasKA requested changes
Der ryger ikke noget på main som ikke er færdigt. (Det kode som jeg smed på main var jo så i også kunne komme i gang med at arbejde ud fra den samme fil struktur, så det lidt en undtagelse)

Husk definition of done. Dine tasks skal virke og være stylet før de kommer på main.
Her er ingen styling, Figma er ikke blevet brugt så du har heller ikke noget styling at gå ud fra, og hvis man klikker slet på 1 arvelader så sletter den hele tablen.

Jeg er ked af at skulle være kritisk, men en feature er først færdig og klar til main, når den er high fidelity. Det her er ikke tæt på

2024-11-13 09:27 UTC, fredforrest commented
> Der ryger ikke noget på main som ikke er færdigt. (Det kode som jeg smed på main var jo så i også kunne komme i gang med at arbejde ud fra den samme fil struktur, så det lidt en undtagelse)
> 
> Husk definition of done. Dine tasks skal virke og være stylet før de kommer på main. Her er ingen styling, Figma er ikke blevet brugt så du har heller ikke noget styling at gå ud fra, og hvis man klikker slet på 1 arvelader så sletter den hele tablen.
> 
> Jeg er ked af at skulle være kritisk, men en feature er først færdig og klar til main, når den er high fidelity. Det her er ikke tæt på

rolig. drik en monster og tæl til 10

2024-11-13 18:32 UTC, L3wis76 commented
ahahah

2024-11-13 19:14 UTC, NillasKA commented
> > Der ryger ikke noget på main som ikke er færdigt. (Det kode som jeg smed på main var jo så i også kunne komme i gang med at arbejde ud fra den samme fil struktur, så det lidt en undtagelse)
> > Husk definition of done. Dine tasks skal virke og være stylet før de kommer på main. Her er ingen styling, Figma er ikke blevet brugt så du har heller ikke noget styling at gå ud fra, og hvis man klikker slet på 1 arvelader så sletter den hele tablen.
> > Jeg er ked af at skulle være kritisk, men en feature er først færdig og klar til main, når den er high fidelity. Det her er ikke tæt på
> 
> rolig. drik en monster og tæl til 10

Sorry D:

2024-11-16 11:41 UTC, closed without merging