Indtast navn
NillasOrg/Arvefordeleren pull request #17
Opened 2024-11-16 11:42 UTC by TheAltintas

Nu skal det virke

2024-11-16 12:05 UTC, NillasKA commented on Components/Pages/Arvinger.razor
I har lavet en non-routable component som kunne bruges i denne klasse.
Den burde faktisk bruges her, men det gør i så overhovedet ikke :(

Den non routable i har lavet bliver aldrig brugt

2024-11-16 12:22 UTC, NillasKA commented on Models/Repositories/ArvingerRepository.cs
> +        private static readonly List<Arving> _arvinger = new List<Arving>();
Hvorfor readonly?

2024-11-16 12:41 UTC, NillasKA requested changes
Nu har jeg stylet det og rettet ret meget i HTML, samt oversat til engelsk.

Nu skal i så bare fikse nogle ting:
Type er familetype og ikke tvangsarv eller friarv, det skal brugeren ikke indtaste selv, det er noget vi styrer i backend.

Derudover er jeres delete mærkelig. Den opdaterer ikke med det samme

Og så please læs mine andre kommentar, de er nyttige for jer selvom jeg selv har rettet de fleste af de fejl

2024-11-18 22:03 UTC, L3wis76 commented
Nu skulle det hele være iorden i think

Fjern knappen opdaterer i realtid. 
Navngivning fra Heris til Heirs fixed - Det var listen der hed det samme som klassenavn der gav problemer

2024-11-18 22:05 UTC, L3wis76 commented
Vælg arving fra listen er ikke inkluderet da jeg syntes det ikke er relevant. 
Vores system tilføjer hvor der bliver gemt i realtid, så der ingen grund til at skulle vælge og redigere når det hele sker i realtid

2024-11-19 09:46 UTC, closed without merging