Indtast navn
NillasOrg/Arvefordeleren pull request #21
Opened 2024-11-19 09:48 UTC by TheAltintas

Nu kan man det man skal og alt burde fungere.

"X" hopper ikke frem og tilbage. (Sidder fast i boksen)

Type af arving er tilbage i form af "Relation" (Barn, Barnebarn, Forældre osv osv.)

2024-11-19 09:49 UTC, NillasKA requested changes

2024-11-19 09:49 UTC, NillasKA commented on Components/Pages/Heirs.razor
> +                <button class="DeleteButton" @onclick="() => RemoveHeir(heir)">&#10005;</button>
Det er stadig ikke det vi aftalte :(

Delete knappen skal være inde i component! Altså inde i den fil

2024-11-19 09:49 UTC, NillasKA commented on Components/Pages/Heirs.razor.css
> +/*.DeleteButton {
Slet, ik udkommenter

2024-11-20 10:41 UTC, L3wis76 commented on Components/Pages/Heirs.razor
> +                <button class="DeleteButton" @onclick="() => RemoveHeir(heir)">&#10005;</button>
Fixed

2024-11-20 11:22 UTC, closed without merging